"""Baseline — the schema as it stood at v0.9.29.

Generated from `app/db/schema.py` against an empty database, so it builds the
whole thing from nothing. That matters for exactly one reason: it is what a
fresh Postgres instance will run.

Databases that predate this revision already have every one of these tables
and must be *stamped*, not upgraded — `app/db/migrate.py` does that
automatically, on the evidence that the app's tables are present while
`alembic_version` is not.

`sde_*` is deliberately absent. CCP's static data is dropped and rebuilt
wholesale on every SDE build, so it is created directly by
`apply_sde_schema()` and kept out of the migration history; see
`migrations/env.py`.

Revision ID: 5c9156e72c43
Revises:
Create Date: 2026-08-18

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9156e72c43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjusted_price_cache',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('adjusted', sa.Float(), nullable=False),
    sa.Column('cached_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('app_bootstrap',
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('app_defaults',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('app_owner',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.Float(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_app_owner_single_row'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_sessions',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('last_seen_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('blueprint_cache',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('blueprint_type_id', sa.Integer(), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('char_assets_cache',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.Float(), nullable=True)
    )
    op.create_table('char_blueprints_cache',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.Float(), nullable=True)
    )
    op.create_table('char_skills_cache',
    sa.Column('character_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('char_wallet_cache',
    sa.Column('character_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('cached_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('characters',
    sa.Column('character_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('character_name', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.Float(), nullable=True),
    sa.Column('corporation_id', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.Float(), nullable=True),
    sa.Column('added_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('corp_assets_cache',
    sa.Column('corporation_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.Float(), nullable=True)
    )
    op.create_table('custom_price_override',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('facility_tax_cache',
    sa.Column('facility_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('cached_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_table('hub_price_cache',
    sa.Column('region_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('cached_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('region_id', 'type_id')
    )
    op.create_table('location_name_cache',
    sa.Column('location_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('margin_snapshot',
    sa.Column('item_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('day', sa.Text(), nullable=False),
    sa.Column('margin_pct', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('item_id', 'day')
    )
    op.create_table('margin_watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('me', sa.Integer(), server_default='0', nullable=False),
    sa.Column('te', sa.Integer(), server_default='0', nullable=False),
    sa.Column('added_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'me', 'te', name='uq_margin_watchlist_item')
    )
    op.create_table('market_hist_etag',
    sa.Column('region_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('etag', sa.Text(), nullable=True),
    sa.Column('days_json', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('region_id', 'type_id')
    )
    op.create_table('market_price_cache',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('cached_at', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('jita_available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('pi_extractor_cache',
    sa.Column('char_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('char_name', sa.Text(), nullable=True),
    sa.Column('planet_name', sa.Text(), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('expiry_iso', sa.Text(), nullable=True),
    sa.Column('cached_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('char_id', 'planet_id', 'product_id')
    )
    op.create_table('planet_name_cache',
    sa.Column('planet_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('planet_id')
    )
    op.create_table('price_history_cache',
    sa.Column('region_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('region_id', 'type_id')
    )
    op.create_table('production_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('runs', sa.Integer(), server_default='1', nullable=False),
    sa.Column('step', sa.Integer(), server_default='1', nullable=False),
    sa.Column('activity', sa.Text(), server_default='manufacturing', nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('product_type_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('me', sa.Integer(), server_default='0', nullable=True),
    sa.Column('te', sa.Integer(), server_default='0', nullable=True),
    sa.Column('station_name', sa.Text(), nullable=True),
    sa.Column('facility_tax', sa.Float(), server_default='0', nullable=True),
    sa.Column('plan_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_shopping',
    sa.Column('project_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('needed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('purchased', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('project_id', 'type_id')
    )
    op.create_table('public_contract_items',
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('is_included', sa.Integer(), nullable=True)
    )
    with op.batch_alter_table('public_contract_items', schema=None) as batch_op:
        batch_op.create_index('idx_pci_contract', ['contract_id'], unique=False)
        batch_op.create_index('idx_pci_type', ['type_id'], unique=False)

    op.create_table('public_contract_meta',
    sa.Column('region_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('indexed_at', sa.Float(), nullable=True),
    sa.Column('contract_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('public_contracts',
    sa.Column('contract_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('collateral', sa.Float(), nullable=True),
    sa.Column('buyout', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('date_expired', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('start_location_id', sa.Integer(), nullable=True),
    sa.Column('end_location_id', sa.Integer(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('contract_id')
    )
    with op.batch_alter_table('public_contracts', schema=None) as batch_op:
        batch_op.create_index('idx_pc_region', ['region_id'], unique=False)

    op.create_table('rig_bonuses',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('set_size', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('me_bonus', sa.Float(), server_default='0', nullable=False),
    sa.Column('te_bonus', sa.Float(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('route_jump_cache',
    sa.Column('sys_a', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('sys_b', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('jumps', sa.Integer(), nullable=False),
    sa.Column('cached_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sys_a', 'sys_b')
    )
    op.create_table('sci_cache',
    sa.Column('solar_system_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('activity', sa.Text(), nullable=False),
    sa.Column('cost_index', sa.Float(), nullable=False),
    sa.Column('cached_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('solar_system_id', 'activity')
    )
    op.create_table('solar_system_cache',
    sa.Column('system_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('security_status', sa.Float(), nullable=True),
    sa.Column('cached_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_table('station_rigs',
    sa.Column('location_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('me_bonus_pct', sa.Float(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('structure_type', sa.Text(), nullable=True),
    sa.Column('rig1_type_id', sa.Integer(), nullable=True),
    sa.Column('rig2_type_id', sa.Integer(), nullable=True),
    sa.Column('rig3_type_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('station_volume_cache',
    sa.Column('location_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('best_sell', sa.Float(), nullable=True),
    sa.Column('traded_volume', sa.Integer(), nullable=True),
    sa.Column('cached_at', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('location_id', 'type_id')
    )
    op.create_table('type_cache',
    sa.Column('type_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('type_cache')
    op.drop_table('station_volume_cache')
    op.drop_table('station_rigs')
    op.drop_table('solar_system_cache')
    op.drop_table('sci_cache')
    op.drop_table('route_jump_cache')
    op.drop_table('rig_bonuses')
    with op.batch_alter_table('public_contracts', schema=None) as batch_op:
        batch_op.drop_index('idx_pc_region')

    op.drop_table('public_contracts')
    op.drop_table('public_contract_meta')
    with op.batch_alter_table('public_contract_items', schema=None) as batch_op:
        batch_op.drop_index('idx_pci_type')
        batch_op.drop_index('idx_pci_contract')

    op.drop_table('public_contract_items')
    op.drop_table('project_shopping')
    op.drop_table('project_plans')
    op.drop_table('project_jobs')
    op.drop_table('production_projects')
    op.drop_table('price_history_cache')
    op.drop_table('planet_name_cache')
    op.drop_table('pi_extractor_cache')
    op.drop_table('market_price_cache')
    op.drop_table('market_hist_etag')
    op.drop_table('margin_watchlist')
    op.drop_table('margin_snapshot')
    op.drop_table('location_name_cache')
    op.drop_table('hub_price_cache')
    op.drop_table('facility_tax_cache')
    op.drop_table('custom_price_override')
    op.drop_table('corp_assets_cache')
    op.drop_table('characters')
    op.drop_table('char_wallet_cache')
    op.drop_table('char_skills_cache')
    op.drop_table('char_blueprints_cache')
    op.drop_table('char_assets_cache')
    op.drop_table('blueprint_cache')
    op.drop_table('app_sessions')
    op.drop_table('app_owner')
    op.drop_table('app_defaults')
    op.drop_table('app_bootstrap')
    op.drop_table('adjusted_price_cache')
    # ### end Alembic commands ###
